---
- name: Install Apache
  apt: 
    pkg: 
    - apache2
    - apache2-utils
    state: present 

- name: Start Apache 
  service: name=apache2 state=started enabled=yes
  ignore_errors: True 

- name: Activate modules
  apache2_module:
    state: present 
    name: rewrite 

- name: Activate modules - cache
  apache2_module:
    state: present 
    name: cache 

- name: Activate modules - headers
  apache2_module:
    state: present 
    name: headers

- name: Activate modules - deflate
  apache2_module:
    state: present 
    name: deflate

- name: Activate modules - expires
  apache2_module:
    state: present 
    name: expires

- name: Copy virtual host
  copy: src=ansible.exampledomain27.pp.ua.conf dest=/etc/apache2/sites-available/ansible.exampledomain27.pp.ua.conf mode=0664

- name: Activate VH 
  shell: a2ensite ansible.exampledomain27.pp.ua
  notify: "Restart apache2"
