---
- include_tasks: variables.yaml
- include_tasks: apache-ubuntu.yaml
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- include_tasks: apache-alma.yaml
  when:
    - ansible_facts['distribution'] == "AlmaLinux"
- include_tasks: php.yaml
- include_tasks: wordpress.yaml
