---
- name: Install php 
  apt: name=libapache2-mod-php state=present

- name: Install other modules
  apt: 
    pkg:
    - php-zip
    - php-xml
    - php-mysql
    - php-gd
    - php-mbstring
    - php-bcmath
    - php-curl
    state: present 

- name: copy php.ini
  copy: 
    src: php.ini 
    dest: /etc/php/7.4/apache2/php.ini 
    mode: 0644
  notify: "Restart apache2"
